version: '3.8'

services:
  db:
    image: postgres:11.2
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - ./.env
  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    volumes:
      - ./bundles-src:/app/bundles-src
      - ./bundles:/app/bundles
    command: >
      sh -c "./node_modules/.bin/parcel watch ./bundles-src/index.js --dist-dir ./bundles --public-url='./'"
  back:
    build:
      context: .
      dockerfile: Dockerfile.back
    volumes:
     - .:/app
    depends_on:
      - db
      - front
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env
    command: >
      bash -c "python manage.py migrate &&  python manage.py runserver 0.0.0.0:8000"

