version: '3.8'

services:
  db:
    image: postgres:11.2
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - ./.env
    restart: always
  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    volumes:
      - ./bundles-src:/app/bundles-src
      - ./bundles:/app/bundles
  back:
    build:
      context: .
      dockerfile: Dockerfile.back
    volumes:
     - .:/app
    depends_on:
      - db
      - front
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env
    command: >
      bash -c "python manage.py migrate --no-input && gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000"
    restart: always
  nginx:
    build: ./nginx
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - 8080:8080
    depends_on:
      - back
    restart: always

