FROM node:16-alpine3.14

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY ./bundles-src ./bundles-src
COPY ./package.json .
COPY ./package-lock.json .
COPY ./assets ./assets

RUN npm ci --include=dev

RUN ./node_modules/.bin/parcel build ./bundles-src/index.js --dist-dir ./bundles --public-url="./"