# Generated by Django 3.2 on 2022-07-18 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_order_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
            preserve_default=False,
        ),
    ]
