# Generated by Django 3.2 on 2022-07-18 14:03

from django.db import migrations


def set_order_item_price(apps, schema_editor):
    OrderMenuItem = apps.get_model('foodcartapp', 'OrderMenuItem')

    for order_item in OrderMenuItem.objects.iterator():
        order_item.price = order_item.product.price
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_ordermenuitem_price'),
    ]

    operations = [
        migrations.RunPython(set_order_item_price)
    ]
