# Generated by Django 3.2 on 2022-07-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20220718_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Необработанный'), ('assembling', 'Сборка'), ('delivering', 'Доставка'), ('done', 'Доставлен')], db_index=True, default='created', max_length=50, verbose_name='Статус'),
        ),
    ]
