# Generated by Django 3.2 on 2022-07-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20220720_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('online', 'Онлайн-оплата'), ('cash', 'Оплата при получении')], db_index=True, max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
