# Generated by Django 3.2 on 2022-08-03 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=60, unique=True, verbose_name='Адрес')),
                ('lat', models.FloatField(verbose_name='Ширина')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата запроса к Геокодеру')),
            ],
        ),
    ]
